name: Customer Panel Laravel CI/CD

on:
  push:
    branches: [server-deploy]
  pull_request:
    branches: [server-deploy]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "7.4"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  deploy:
    name: Deploy and Setup
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: ngocquyhoang/deploy@laravel
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.HOST }}
          path: ${{ secrets.PATH }}
          owner: ${{ secrets.OWNER }}
        env:
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}

      - name: Run a script on remote server (setup)
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PATH }} && composer install && find . -type f -exec chmod 644 {} \; && find . -type d -exec chmod 755 {} \; &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"
          # The & in the command runs the process on background
