name: Customer Panel Laravel CI/CD

on:
  push:
    branches: [server-deploy]
  pull_request:
    branches: [server-deploy]

jobs:
  deploy:
    name: Deploy and Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: ngocquyhoang/deploy@laravel
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.HOST }}
          path: ${{ secrets.PATH }}
          owner: ${{ secrets.OWNER }}
        env:
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}

      - name: Run a script on remote server (setup)
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PATH }} \
              composer install \
              composer dumpautoload -o \
              php artisan optimize --force \
              php artisan config:cache \
              php artisan route:cache \
              find . -type f -exec chmod 644 {} \; \
              find . -type d -exec chmod 755 {} \; &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"
          # The & in the command runs the process on background
